buttontype = "a"
sitname = "Yggdrasil Games"
sitid = "ygg"
sitsubid = "top"
baseadd = "file://c:/download/softworlds/yggdrasil"
homdress = "file://c:/download/wmonline/index.html"
barlog = "file://c:/download/softworlds/images/wm.gif"
sitlog = "file://c:/download/softworlds/yggdrasil/bar.jpg"
sw = "file://c:/download/softworlds";
ygg = "file://c:/download/softworlds/yggdrasil";
az = "file://c:/download/softworlds/pork";
