sitname = "Azeroth: Legacy"
sitid = "az"
sitsubid = "top"
baseadd = "http://sw.itgo.com/azeroth"
homdress = "http://members.xoom.com/WrldMakr/index.html"
barlog = "http://sw.itgo.com/images/wm.gif"
sitlog = "http://sw.itgo.com/azeroth/bar.jpg"
